keycloak-issuer: http://localhost/auth/realms/openslice

server:
  port: 13011
    

logging:
  level:
    root: INFO
    org.apache.camel.zipkin: INFO
    org.apache.camel.spring.cloud: INFO
    org.apache.camel: INFO
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger %M %L:  %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
        
    
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: mano-client-service
  activemq:
    brokerUrl: tcp://localhost:61616?jms.watchTopicAdvisories=false
    user: artemis
    password: artemis
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
                
portaltitle: "openslice"
maindomain: "http://localhost:13000"
main_operations_product: "Openslice Operations"

keycloak:
  realm: openslice
  auth-server-url: http://localhost/auth
  ssl-required: none
  resource: admin-cli
  credentials:
    secret: none
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username

#ALARMS
ALARMS_ADD_ALARM: "jms:queue:ALARMS.ADD.ALARM"
ALARMS_UPDATE_ALARM: "jms:queue:ALARMS.UPDATE.ALARM"
ALARMS_GET_ALARM: "jms:queue:ALARMS.GET.ALARM"


#NS ACTIONS
NFV_CATALOG_NSACTIONS_SCALE: "jms:queue:NSACTIONS.SCALE"
NFV_CATALOG_NS_LCMCHANGED: "jms:topic:NFV_CATALOG_NS_LCMCHANGED"


