
# For Spring Actuator /info endpoint
info:
    artifact: mano-client-service
    name: mano-client-service
    description: Spring mano-client-service
    version: 1.0.0

server:
  port: 13011
    

logging:
  level:
    org.springframework.cloud.consul: INFO
    org.apache.camel.zipkin: INFO
    org.apache.camel.spring.cloud: INFO
    org.apache.camel: INFO
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
        
# Camel Service Call
camel:
  cloud:
    service-call.component: undertow
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
    server-service-mappings.[*]: mano-client-service
    client-service-mappings.[*]: mano-client-service
    include-message-body-streams: false
    
    
spring:
  profiles: default
  application:
    name: mano-client-service
  cloud:
    consul:
      enabled: true
      host: http://localhost
      port: 8500
      config:
        enabled: true
        prefix: config
        defaultContext: openslice
        data-key: osdata
        profileSeparator: '::'
        format: yaml
      discovery:        
        tags: openslice-microservice
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckInterval: 120s
      
  activemq:
    brokerUrl: tcp://localhost:6616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true
      
portaltitle: "openslice"
maindomain: "http://localhost:13000"
main_operations_product: "Openslice Operations"

keycloak:
  realm: openslice
  auth-server-url: http://localhost/auth
  ssl-required: none
  resource: admin-cli
  credentials:
    secret: none
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username

#ALARMS
ALARMS_ADD_ALARM: "jms:queue:ALARMS.ADD.ALARM"
ALARMS_UPDATE_ALARM: "jms:queue:ALARMS.UPDATE.ALARM"
ALARMS_GET_ALARM: "jms:queue:ALARMS.GET.ALARM"


#NS ACTIONS
NFV_CATALOG_NSACTIONS_SCALE: "jms:queue:NSACTIONS.SCALE"
NFV_CATALOG_NS_LCMCHANGED: "jms:topic:NFV_CATALOG_NS_LCMCHANGED"


